EXCLUDED_FIELDS = {
    # general
    '_id': False, 
    'properties.optional': False, 
    'properties.required.years': False, 
    # coal mines
    'properties.original.county': False,
    'properties.original.msha_id': False,
    'properties.original.namemsha': False,
    'properties.original.notes': False,
    'properties.original.year': False,
    # gas pipelines
    'properties.original.OperatorNa': False,
    'properties.original.Source': False,
    # oil pipelines
    'properties.original.Opername': False,
    'properties.original.Pipename': False,
    'properties.original.Shape_Leng': False,
    # petroleum product pipelines
    # biodiesel
    'properties.original.Company': False,
    'properties.original.Data_Perio': False,
    'properties.original.PADD': False,
    'properties.original.State': False,
    # gas underground storage
    'properties.original.AGARegion': False,
    'properties.original.CompanyNam': False,
    'properties.original.CountyName': False,
    'properties.original.FieldName': False,
    'properties.original.FieldType': False,
    'properties.original.MaximumDai': False,
    'properties.original.ReportPeri': False,
    'properties.original.ReservoirN': False,
    'properties.original.Status': False,
    'properties.original.TotalField': False,
    # gotta keep lat for gas processing unless we process it differently
    # 'properties.original.lat': False,
    'properties.original.long_': False,
    # active platforms
    'properties.original.AREA': False,
    'properties.original.COMPLEX_ID': False,
    'properties.original.INSTALL': False,
    'properties.original.INSTALL_DA': False,
    'properties.original.PERIMETER': False,
    'properties.original.PLATFORM_': False,
    'properties.original.PLATFORM_I': False,
    'properties.original.REMOVAL': False,
    'properties.original.REMOVAL_DA': False,
    'properties.original.STR_NAME': False,
    'properties.original.STR_NUMBER': False,
    # petroleum product terminals
    'properties.original.Data_perio': False,
    'properties.original.Site_Name': False,
    # import terminals
    'properties.original.City': False,
    'properties.original.County': False,
    'properties.original.Function': False,
    'properties.original.Owner': False,
    'properties.original.Regas_Cap': False,
    'properties.original.Terminal': False,
    # petroleum refineries
    'properties.original.COMPANY_NA': False,
    'properties.original.CORPORATIO': False,
    'properties.original.PERIOD': False,
    'properties.original.SITE': False,
    'properties.original.STATE_NAME': False,
    # keep the following because they're used 
    # on the front end
    # 'properties.original.Alky_Iso': False,
    # 'properties.original.Atm_Dist': False,
    # 'properties.original.Cat_Crack': False,
    # 'properties.original.Cat_Reform': False,
    # 'properties.original.Coking': False,
    # 'properties.original.Desulfur': False,
    # 'properties.original.Hydro_Crac': False,
    # 'properties.original.Vac_Dist': False,
    # 'properties.original.Visbreak': False,
    # power plants
    'properties.original.Capacity_b': False,
    'properties.original.PLANT_NAME': False,
    'properties.original.PrimaryFue': False,
    'properties.original.UTILITY_ID': False,
    'properties.original.UTILITY_NA': False,
    'properties.original.cap_bio': False,
    'properties.original.cap_coal': False,
    'properties.original.cap_geo': False,
    'properties.original.cap_hydro': False,
    'properties.original.cap_ng': False,
    'properties.original.cap_nuc': False,
    'properties.original.cap_other': False,
    'properties.original.cap_otherf': False,
    'properties.original.cap_pet': False,
    'properties.original.cap_pump': False,
    'properties.original.cap_solar': False,
    'properties.original.cap_wind': False,
    'properties.original.cap_wood': False,
    'properties.original.plant_code': False,
    # keep primary_fu bc the front end uses that field for drawing
    # 'properties.original.primary_fu': False,
    'properties.original.producer_t': False,
    # processing plants
    'properties.original.BTU_Conten': False,
    'properties.original.DryGasStor': False,
    'properties.original.NG_LiquidS': False,
    'properties.original.OperatorCo': False,
    'properties.original.OwnerCompa': False,
    'properties.original.PlantFlow': False,
    'properties.original.Plant_Name': False,
    'properties.original.ZipCode': False,
    # railroads
    'properties.original.FNODE_': False,
    'properties.original.LENGTH': False,
    'properties.original.MARK1': False,
    'properties.original.MARK2': False,
    'properties.original.MARK3': False,
    'properties.original.RAILRDL020': False,
    'properties.original.RROWNER1': False,
    'properties.original.RROWNER2': False,
    'properties.original.RROWNER3': False,
    'properties.original.TNODE_': False,
    # petroleum strategic reserves
    'properties.original.Caverns': False,
    'properties.original.Name': False,
    # shale
    'properties.original.Age_color': False,
    'properties.original.Age_shale': False,
    'properties.original.Area_sq_km': False,
    'properties.original.Basin': False,
    'properties.original.Lithology': False,
    'properties.original.Shale_play': False,
    # wells tx capcog
    'properties.original.COUNTY_COD': False,
    'properties.original.ELEVATION_': False,
    'properties.original.FEATURE_fi': False,
    'properties.original.OBJECT': False,
    'properties.original.OWNER': False,
    'properties.original.PRIMARY_US': False,
    'properties.original.WATER_LEVE': False,
    'properties.original.WATER_QUAL': False,
    'properties.original.WELLNUMBER': False,
    'properties.original.WELL_DEPTH': False,
    'properties.original.WELL_TYPE': False,
    # processing/gas
    'properties.original.index': False,
}